### ISSUE TITLE
`dak.where`

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#127]
Not implemented:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask_awkward/lib/structure.py", line 503, in where
    raise DaskAwkwardNotImplemented("TODO")
dask_awkward.utils.DaskAwkwardNotImplemented: TODO

If you would like this unsupported call to be supported by
dask-awkward please open an issue at:
https://github.com/dask-contrib/dask-awkward.
```

**Comment by masonproffitt** [comment]
Main use case here is if you need to apply different selection criteria based on the value of another field (e.g., different pT requirements in different regions of eta). This is one is maybe lower priority, as I haven't found myself using it as much and there are relatively easy ways to work around it (by using combinations of other logical operations)
