### ISSUE TITLE
Applying a mask to an array from `uproot.dask` drops other fields

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#134]
I'm not exactly sure if the problem here is in Uproot, Awkward Array, or `dask-awkward`. The file I'm using here is <https://github.com/iris-hep/func_adl_uproot/blob/174306406269f7a64df068483c76c566a7c4857a/tests/scalars_tree_file.root>, though I assume this isn't file specific.

```python
>>> import uproot, awkward as ak, dask_awkward as dak
>>> uproot.__version__
'5.0.1'
>>> ak.__version__
'2.0.2'
>>> dak.__version__
'2022.12.0'
>>> da = uproot.dask('tests/scalars_tree_file.root')
>>> da.fields
['int_branch', 'long_branch', 'float_branch', 'double_branch', 'bool_branch']
>>> da[da.int_branch < 0].fields
['int_branch', 'long_branch', 'float_branch', 'double_branch', 'bool_branch']
>>> da[da.int_branch < 0].compute().fields
['int_branch']
>>> da[da.int_branch < 0].long_branch.compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/highlevel.py", line 962, in __getitem__
    out = self._layout[where]
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/contents/content.py", line 493, in __getitem__
    return self._getitem(where)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/contents/content.py", line 506, in _getitem
    return self._getitem_field(where)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/contents/indexedarray.py", line 217, in _getitem_field
    self._content._getitem_field(where, only_fields),
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/contents/recordarray.py", line 318, in _getitem_field
    return self.content(where)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/contents/recordarray.py", line 271, in content
    out = self.form_cls.content(self, index_or_field)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/forms/recordform.py", line 151, in content
    index = self.field_to_index(index_or_field)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/contents/recordarray.py", line 265, in field_to_index
    return self.form_cls.field_to_index(self, field)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/awkward/forms/recordform.py", line 128, in field_to_index
    raise ak._errors.wrap_error(
IndexError: while attempting to slice

    <Array [{int_branch: -1}] type='1 * {int_branch: int32}'>

with

    'long_branch'

Error details: no field 'long_branch' in record with 1 fields
```

As you can see, after slicing with `da[da.int_branch < 0]`, the other branches are supposed to still be there, but they seem to disappear after running `.compute()`

**Comment by douglasdavis** [comment]
Yea this should be fixed by #131

**Comment by douglasdavis** [comment]
I was able to test it with the file you linked- now there's an issue with uproot :) I'll create a PR

**Comment by douglasdavis** [comment]
Ok #131 _combined_ with https://github.com/scikit-hep/uproot5/pull/806 should fix this.
