### ISSUE TITLE
Unable to use a concatenated array of records in masks

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#188]
For example:

```python
>>> import awkward as ak, dask_awkward as dak
>>> a = ak.Array([[{'a': 1}]])
>>> da = dak.from_awkward(a, 1)
>>> da_concat = dak.concatenate([da, da], axis=1)
>>> da_concat.compute()
<Array [[{a: 1}, {a: 1}]] type='1 * var * {a: int64}'>
>>> da_concat[da_concat.a > 0]
Traceback (most recent call last):
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 876, in _getitem_single
    dtype = where.layout.dtype.type
AttributeError: 'ListOffsetArray' object has no attribute 'dtype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 922, in __getitem__
    return self._getitem_single(where)
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 878, in _getitem_single
    dtype = where.layout.content.dtype.type
AttributeError: 'IndexedArray' object has no attribute 'dtype'

```

**Comment by masonproffitt** [comment]
Specifically, it _is_ possible to mask the concatenated array (with some other unrelated array):

```python
>>> mask = dak.from_awkward(ak.Array([[True, True]]), 1)
>>> da_concat[mask].compute()
<Array [[{a: 1}, {a: 1}]] type='1 * var * {a: int64}'>
```

but it's not possible to mask _any_ array with a field of the concatenated record array:

```python
>>> mask[da_concat.a > 0].compute()
Traceback (most recent call last):
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 876, in _getitem_single
    dtype = where.layout.dtype.type
AttributeError: 'ListOffsetArray' object has no attribute 'dtype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 922, in __getitem__
    return self._getitem_single(where)
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 878, in _getitem_single
    dtype = where.layout.content.dtype.type
AttributeError: 'IndexedArray' object has no attribute 'dtype'
```

For reference, this is the expected behavior from awkward:

```python
>>> a_concat = ak.concatenate([a, a], axis=1)
>>> a_concat[a_concat.a > 0]
<Array [[{a: 1}, {a: 1}]] type='1 * var * {a: int64}'>
```
