### ISSUE TITLE
Cannot run compute simultaneously with multiple different input layers

### ISSUE THREAD

**Issue by lgray** [dask-contrib/dask-awkward#299]
This has definitely worked in the past and is obviously useful functionality!

```python3
import uproot
import dask


if __name__ == "__main__":
    events_zjets = uproot.dask(
        {"https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root": "Events"}
    )

    events_dimuon = uproot.dask(
        {"https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dimuon.root": "Events"}
    )

    print(dask.compute(events_zjets.Muon_pt, events_dimuon.Muon_pt, scheduler="processes"))
```

now fails with:
```
Traceback (most recent call last):
  File "what.py", line 14, in <module>
    print(dask.compute(events_zjets.Muon_pt, events_dimuon.Muon_pt, scheduler="processes"))
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/base.py", line 599, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/multiprocessing.py", line 233, in get
    result = get_async(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/local.py", line 318, in reraise
    raise exc.with_traceback(tb)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 1492, in __call__
    return self.fn(*args, **kwargs)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 962, in __getitem__
    return wrap_layout(out, self._behavior, allow_other=True)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_errors.py", line 56, in __exit__
    self.handle_exception(exception_type, exception_value)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_errors.py", line 71, in handle_exception
    raise self.decorate_exception(cls, exception)
awkward._errors.FieldNotFoundError: no field 'Muon_pt' in record with 1 fields

This error occurred while attempting to slice

    <Array [{run: 315267}, {...}, ..., {run: 315267}] type='40 * {run: uint32}'>

with

    'Muon_pt'
```

**Comment by lgray** [comment]
@douglasdavis (I know you've seen this but pinging anyway)

**Comment by lgray** [comment]
Hmm just tried multiple versions back and I can't get a recipe where it works, I've for sure done this, but probably more towards the beginning of the year.

**Comment by douglasdavis** [comment]
OK I'll just get working on it with the reproducer. Knowing it's not a recent change is still good info :P

**Comment by douglasdavis** [comment]
Been banging my head on this for a while and still at it.

At a high level the problem is that `dask.base.collections_to_dsk` (a function that takes multiple graphs and merges them into one) is doing something that our column optimization is not compatible with.

**Comment by douglasdavis** [comment]
Our column optimization is designed for a graph that topologically has a single output layer key. We compute the typetracer a bit manually, by asking dask to give us a specific key from a graph (the graph is the one we've constructed to be typetracer only, the key is what we expect to be the final leaf node in a graph)

https://github.com/dask-contrib/dask-awkward/issues/new?permalink=https%3A%2F%2Fgithub.com%2Fdask-contrib%2Fdask-awkward%2Fblob%2Fc00b6d3ba247e7f22190ba636c9a68132672574d%2Fsrc%2Fdask_awkward%2Flib%2Foptimize.py%23L369-L375

When computing one collection this is going to be fine. If there are multiple collections getting computed, we expect multiple "result" leaf nodes at the bottom of the graph. THe `HighLevelGraph._toposort_layers()` method is going to bury one "result" layers. We need to find a way to make sure we call `get_sync` for not just the last key we get from toposort_layers, but for any key that is a leaf node.
