### ISSUE TITLE
dak.ones_like / zeros_like fails

### ISSUE THREAD

**Issue by lgray** [dask-contrib/dask-awkward#314]
Caught another one trying to figure out why `dak.count(events.event, axis=0)` is so slow.
Was attempting to do `dak.sum(dak.ones_like(events.event), axis=0)` but ran what's reproduced below.
Same error for zeros_like, since it's coming from full_like.

```python3
import uproot
import awkward as ak
import dask_awkward as dak

tree = uproot.open({"https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root": "Events"})
dtree = uproot.dask(tree)
    
print(ak.ones_like(tree["event"].array()))

print(dak.ones_like(dtree.event).compute())
```

fails with:
```
Traceback (most recent call last):
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_dispatch.py", line 43, in dispatch
    next(gen_or_result)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_ones_like.py", line 38, in ones_like
    return _impl(array, highlevel, behavior, dtype, including_unknown)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_ones_like.py", line 42, in _impl
    return ak.operations.ak_full_like._impl(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_full_like.py", line 205, in _impl
    out = ak._do.recursively_apply(layout, action, behavior)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_do.py", line 35, in recursively_apply
    return layout._recursively_apply(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/contents/numpyarray.py", line 1258, in _recursively_apply
    result = action(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_full_like.py", line 119, in action
    nplike.ones_like(original, dtype=dtype),
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_nplikes/array_module.py", line 87, in ones_like
    assert not isinstance(x, PlaceholderArray)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ones_like_repro.py", line 10, in <module>
    print(dak.ones_like(dtree.event).compute())
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/base.py", line 314, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/base.py", line 599, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 1492, in __call__
    return self.fn(*args, **kwargs)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_dispatch.py", line 51, in dispatch
    return gen_or_result
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_errors.py", line 63, in __exit__
    self.handle_exception(exception_type, exception_value)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_errors.py", line 78, in handle_exception
    raise self.decorate_exception(cls, exception)
AssertionError: 

See if this has been reported at https://github.com/scikit-hep/awkward/issues
```

**Comment by douglasdavis** [comment]
Ah with count acting wonky and now ones_like and zeros_like, along with with the apparent eager compute happening (that I mentioned here https://github.com/dask-contrib/dask-awkward/issues/313#issuecomment-1625550824), it seems like we have an ugly regression somewhere,

**Comment by lgray** [comment]
Just to post it out of slack, since we're starting to see the outline of failures, here's a version matrix of failures in coffea:
https://github.com/CoffeaTeam/coffea/pulls?q=is%3Apr+is%3Aopen+%22version+scan%22

**Comment by douglasdavis** [comment]
same failure as this: https://github.com/dask-contrib/dask-awkward/issues/313#issuecomment-1634936839 with the latest release (2023.7.1)

**Comment by douglasdavis** [comment]
"merging" this in with #313
